# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-07 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('county', models.CharField(choices=[('DUBLIN', 'Dublin'), ('KILDARE', 'Kildare'), ('CORK', 'Cork'), ('MEATH', 'Meath'), ('LAOIS', 'Laois')], default='None', max_length=15)),
                ('contact_number', models.CharField(blank=True, max_length=12, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
