# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-08 07:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clockings', '0002_auto_20201007_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clocking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_clockings', models.IntegerField(default=0)),
                ('clocking_in_time', models.DateTimeField(blank=True)),
                ('clocking_out_time', models.DateTimeField(blank=True)),
                ('lunch_out_time', models.DateTimeField(blank=True)),
                ('lunch_in_time', models.DateTimeField(blank=True)),
                ('clocking_date', models.DateField(auto_now=True)),
                ('officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
