# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-08 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockings', '0003_clocking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clocking',
            name='clocking_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clocking',
            name='clocking_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clocking',
            name='lunch_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clocking',
            name='lunch_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
