# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-08 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clockings', '0004_auto_20201008_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteClock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_number_of_clockings', models.IntegerField(default=0)),
                ('remote_clock_in_location', models.CharField(blank=True, max_length=200, null=True)),
                ('remote_clocking_in_time', models.DateTimeField(blank=True, null=True)),
                ('remote_lunch_out_location', models.CharField(blank=True, max_length=200, null=True)),
                ('remote_lunch_out_time', models.DateTimeField(blank=True, null=True)),
                ('remote_lunch_in_location', models.CharField(blank=True, max_length=200, null=True)),
                ('remote_lunch_in_time', models.DateTimeField(blank=True, null=True)),
                ('remote_clock_out_location', models.CharField(blank=True, max_length=200, null=True)),
                ('remote_clocking_out_time', models.DateTimeField(blank=True, null=True)),
                ('remote_clocking_date', models.DateTimeField(auto_now=True)),
                ('remote_clock_officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_clock_officer_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
