# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-14 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clockings', '0005_remoteclock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualClocking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clocking_date', models.DateField()),
                ('clocking_in_time', models.TimeField()),
                ('clocking_out_time', models.TimeField()),
                ('lunch_out_time', models.TimeField()),
                ('lunch_in_time', models.TimeField()),
                ('reason_for_missed_clocking', models.CharField(max_length=200)),
                ('checked_by_validator', models.BooleanField(default=False)),
                ('mc_officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mc_officer_id', to=settings.AUTH_USER_MODEL)),
                ('validator_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validator_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
