# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-16 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockings', '0006_manualclocking'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualclocking',
            name='accept_reject_clock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manualclocking',
            name='reason_manual_clock_rejected',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='roster_side',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='None', max_length=2),
        ),
        migrations.AlterField(
            model_name='clocking',
            name='clocking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clocking',
            name='clocking_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clocking',
            name='clocking_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clocking',
            name='lunch_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clocking',
            name='lunch_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
